# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Douglas Halley
tagline:          My Development Blog
description:      A blog for my ventures into Python, Maya, Houdini, UE4, and beyond.
url:              https://douglascomet.github.io
baseurl:
paginate:         5
name:             Doug Halley

gems:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-gist

# SEO
social:
  name:           Douglas Halley
  links:
    - https://www.linkedin.com/in/raymonddhalley/
    - https://raymonddhalley.wixsite.com/portfolio
    - https://github.com/douglascomet


# Custom vars
custom_pages:
  feed:               /atom.xml
github:
  url:                https://github.com/douglascomet
  repo:               https://github.com/douglascomet/douglascomet.github.io
google_analytics:     UA-70773524-1
show_related_posts:   false
force_https:          true

# Plugins
# plugins:
#   - jekyll-seo-tag

# Comments
# comments:
#   use_disqus:         true
#   use_googleplus:     false
#   disqus_shortname:   douglascomet

