# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Douglas Halley
tagline:          My Development Blog
description:      A blog for my ventures into Python, Maya, Houdini, UE4, and beyond.
url:              https://douglascomet.github.io
baseurl:          /

paginate:         5

social:
  name:           Douglas Halley
  links:
    - https://www.linkedin.com/in/raymonddhalley/
    - https://raymonddhalley.wixsite.com/portfolio
    - https://github.com/douglascomet
